package ui;
import model.Certificate;
import java.text.SimpleDateFormat;

public class CertificateDialog extends javax.swing.JDialog {
    private Certificate certificate;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CertificateDialog.class.getName());

      public CertificateDialog(java.awt.Frame parent, Certificate cert) {
        super(parent, true);
        initComponents();
        this.certificate = cert;
        populateCertificateData();  // This fills in all the data
        setLocationRelativeTo(parent);
    }
      private void populateCertificateData() {
        // Get student name from certificate and display it
        studentNameLabel.setText(certificate.getStudentName());
        
        // Get course title from certificate and display it
        courseTitleLabel.setText(certificate.getCourseTitle());
        
        // Get final score from certificate and display it with formatting
        scoreLabel.setText(String.format("Final Score: %.1f%%", certificate.getFinalScore()));
        
        // Get instructor name from certificate and display it
        instructorLabel.setText("Instructor: " + certificate.getInstructorName());
        
        // Format the date nicely (e.g., "November 24, 2025")
        SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd, yyyy");
        dateLabel.setText("Issue Date: " + sdf.format(certificate.getIssueDate()));
        
        // Format certificate ID with leading zeros (e.g., CERT-0001)
        certIdLabel.setText("Certificate ID: CERT-" + String.format("%04d", certificate.getCertificateID()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        courseTitleLabel = new javax.swing.JLabel();
        scorePanel = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        instructorLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        certIdLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        printBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Certificate of Completion");
        setModal(true);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(240, 248, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 134, 11), 8), javax.swing.BorderFactory.createEmptyBorder(30, 40, 30, 40)));

        headerPanel.setBackground(new java.awt.Color(240, 248, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(184, 134, 11));
        jPanel1.setMaximumSize(new java.awt.Dimension(3000, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        headerPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 25, 112));
        jLabel2.setText(" 🏆 Certificate of Completion");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 70, 70));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("This certifies that");
        contentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 592, -1));

        studentNameLabel.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        studentNameLabel.setForeground(new java.awt.Color(184, 134, 11));
        studentNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentNameLabel.setText("[Student Name]");
        contentPanel.add(studentNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 310, 60));

        jLabel4.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("has successfully completed the course");
        contentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        courseTitleLabel.setFont(new java.awt.Font("Serif", 1, 26)); // NOI18N
        courseTitleLabel.setForeground(new java.awt.Color(25, 25, 112));
        courseTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        courseTitleLabel.setText("[Course Title]");
        contentPanel.add(courseTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        scorePanel.setBackground(new java.awt.Color(240, 255, 240));
        scorePanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(34, 139, 34), 2)));

        scoreLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(0, 100, 0));
        scoreLabel.setText("Final Score: 95.0%");

        javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(scorePanel);
        scorePanel.setLayout(scorePanelLayout);
        scorePanelLayout.setHorizontalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(scoreLabel)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        scorePanelLayout.setVerticalGroup(
            scorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scorePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scoreLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        contentPanel.add(scorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 410, 60));

        instructorLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        instructorLabel.setForeground(new java.awt.Color(50, 50, 50));
        instructorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructorLabel.setText("Instructor: [Name]");
        contentPanel.add(instructorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        dateLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(128, 128, 128));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("Issue Date: [Date]");
        dateLabel.setToolTipText("");
        contentPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        certIdLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        certIdLabel.setForeground(new java.awt.Color(128, 128, 128));
        certIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        certIdLabel.setText("Certificate ID: CERT-0001");
        contentPanel.add(certIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        buttonPanel.setOpaque(false);

        printBtn.setBackground(new java.awt.Color(70, 130, 180));
        printBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printBtn.setForeground(new java.awt.Color(255, 255, 255));
        printBtn.setText("Print Certificate");
        printBtn.setBorderPainted(false);
        printBtn.setFocusPainted(false);
        printBtn.setPreferredSize(new java.awt.Dimension(150, 35));
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(149, 165, 166));
        closeBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("Close");
        closeBtn.setBorderPainted(false);
        closeBtn.setFocusPainted(false);
        closeBtn.setPreferredSize(new java.awt.Dimension(100, 35));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
this.dispose();     }//GEN-LAST:event_closeBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
javax.swing.JOptionPane.showMessageDialog(this, 
        "Print functionality coming soon!", 
        "Print", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_printBtnActionPerformed

     
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel certIdLabel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel courseTitleLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JLabel studentNameLabel;
    // End of variables declaration//GEN-END:variables

}