package ui;

import javax.swing.*;
import model.Student;
import model.Course;
import service.StudentService;
import java.util.List;
import service.CertificateService;
import service.CourseCompletionTracker;
import model.Certificate;
import java.awt.*;
import java.awt.event.ActionEvent;
import database.JsonDatabaseManager;
import java.awt.event.ActionListener;


public class StudentDashboardFrame extends javax.swing.JPanel {
 private Student student;            
    private StudentService service; 
    /**
     * Creates new form StudentDashboardFrame
     */
    public StudentDashboardFrame(model.Student student, service.StudentService service) {
    initComponents();
    this.student = student;
    this.service = service;
    loadAvailableCourses();
    loadEnrolledCourses();
    setupUI();
}
private void setupUI() {
        // Make the title more visible
        titleLabel.setText("Student Dashboard - Welcome " + student.getUsername());
           }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        enrolledPanel = new javax.swing.JPanel();
        enrolledLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enrolledList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        openBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        certificatesBtn = new javax.swing.JButton();
        availablePanel = new javax.swing.JPanel();
        availableLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        enrollBtn = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(240, 242, 245));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 350));

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(41, 128, 185));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Student Dashboard");

        logoutBtn.setBackground(new java.awt.Color(231, 76, 60));
        logoutBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        enrolledPanel.setBackground(new java.awt.Color(255, 255, 255));
        enrolledPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220))));

        enrolledLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        enrolledLabel.setForeground(new java.awt.Color(52, 73, 94));
        enrolledLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enrolledLabel.setText("My Courses");

        enrolledList.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        enrolledList.setFixedCellHeight(45);
        enrolledList.setSelectionBackground(new java.awt.Color(52, 152, 219));
        enrolledList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(enrolledList);

        openBtn.setBackground(new java.awt.Color(46, 204, 113));
        openBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        openBtn.setForeground(new java.awt.Color(255, 255, 255));
        openBtn.setText("Open Course");
        openBtn.setBorderPainted(false);
        openBtn.setFocusPainted(false);
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(149, 165, 166));
        refreshBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.setBorderPainted(false);
        refreshBtn.setFocusPainted(false);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        certificatesBtn.setBackground(new java.awt.Color(255, 215, 0));
        certificatesBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        certificatesBtn.setText("My Certificates");
        certificatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificatesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(openBtn)
                .addGap(18, 18, 18)
                .addComponent(refreshBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(certificatesBtn)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openBtn)
                    .addComponent(refreshBtn))
                .addGap(5, 5, 5)
                .addComponent(certificatesBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout enrolledPanelLayout = new javax.swing.GroupLayout(enrolledPanel);
        enrolledPanel.setLayout(enrolledPanelLayout);
        enrolledPanelLayout.setHorizontalGroup(
            enrolledPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolledPanelLayout.createSequentialGroup()
                .addGroup(enrolledPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enrolledLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enrolledPanelLayout.setVerticalGroup(
            enrolledPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolledPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(enrolledLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        availablePanel.setBackground(new java.awt.Color(255, 255, 255));
        availablePanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220))));

        availableLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        availableLabel.setForeground(new java.awt.Color(52, 73, 94));
        availableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        availableLabel.setText("Available Courses");

        availableList.setFixedCellHeight(45);
        availableList.setSelectionBackground(new java.awt.Color(52, 152, 219));
        availableList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(availableList);

        enrollBtn.setBackground(new java.awt.Color(41, 128, 185));
        enrollBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enrollBtn.setForeground(new java.awt.Color(255, 255, 255));
        enrollBtn.setText("Enroll in Course");
        enrollBtn.setBorderPainted(false);
        enrollBtn.setFocusPainted(false);
        enrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(enrollBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enrollBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout availablePanelLayout = new javax.swing.GroupLayout(availablePanel);
        availablePanel.setLayout(availablePanelLayout);
        availablePanelLayout.setHorizontalGroup(
            availablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availablePanelLayout.createSequentialGroup()
                .addGroup(availablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(availablePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(availableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        availablePanelLayout.setVerticalGroup(
            availablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(availablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enrolledPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(availablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(enrolledPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(logoutBtn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
       String selected = enrolledList.getSelectedValue();
    
    // Check if selected
    if (selected == null) {
        JOptionPane.showMessageDialog(this, "Please select a course!");
        return;
    }
    
    try {
        // Get course ID
        String[] parts = selected.split(" - ");
        int courseId = Integer.parseInt(parts[0]);
        String courseName = parts[1];
        
        // Check for certificate
        JsonDatabaseManager db = new JsonDatabaseManager();
        CertificateService cs = new CertificateService(db);
        
        // Check if completed
        if (cs.isEligibleForCertificate(student.getUserId(), String.valueOf(courseId))) {
            // Check if already has certificate
            Certificate exist = cs.getCertificateForCourse(student.getUserId(), String.valueOf(courseId));
            
            if (exist == null) {
                // Make new certificate
                Certificate newCert = cs.generateCertificate(student.getUserId(), String.valueOf(courseId));
                
                if (newCert != null) {
                    JOptionPane.showMessageDialog(this, 
                        "Congratulations! You earned a certificate!\nCheck 'My Certificates' button.");
                }
            }
        }
        
        // Open course details
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        CourseDetailsDialog dialog = new CourseDetailsDialog(parent, student, service, courseId, courseName);
        dialog.setVisible(true);
        
        // Refresh
        loadEnrolledCourses();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_openBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadAvailableCourses();
        loadEnrolledCourses();
        JOptionPane.showMessageDialog(this, 
            "Course lists refreshed!", 
            "Refreshed", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void enrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollBtnActionPerformed
String selected = availableList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, 
                "Please select a course from 'Available Courses' first!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int courseId = Integer.parseInt(selected.split(" - ")[0]);
            
            boolean ok = service.enrollInCourse(student.getUserId(), courseId);
            
            if (ok) {
                JOptionPane.showMessageDialog(this, 
                    "Successfully enrolled in the course!", 
                    "Enrollment Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                loadEnrolledCourses();
                loadAvailableCourses();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "You are already enrolled in this course!", 
                    "Already Enrolled", 
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "An error occurred during enrollment: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enrollBtnActionPerformed

    private void certificatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificatesBtnActionPerformed
    JsonDatabaseManager db = new JsonDatabaseManager();
    CertificateService cs = new CertificateService(db);
    
    // Get certificates
    List<Certificate> myCerts = cs.getStudentCertificates(student.getUserId());
    
    // Make a dialog
    JDialog dialog = new JDialog();
    dialog.setTitle("My Certificates");
    dialog.setSize(650, 450);
    dialog.setLocationRelativeTo(this);
    dialog.setModal(true);
    
    // Make main panel
    JPanel panel = new JPanel();
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
    panel.setBackground(Color.WHITE);
    
    // Add title
    JLabel title = new JLabel("My Certificates");
    title.setFont(new Font("Arial", Font.BOLD, 20));
    panel.add(title);
    panel.add(Box.createVerticalStrut(10));
    
    // Check if empty
    if (myCerts.size() == 0) {
        JLabel noLabel = new JLabel("No certificates yet!");
        noLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        panel.add(noLabel);
    } else {
        // Show each certificate
        for (int i = 0; i < myCerts.size(); i++) {
            Certificate c = myCerts.get(i);
            
            // Make a panel for this certificate
            JPanel certPanel = new JPanel();
            certPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
            certPanel.setBackground(new Color(240, 240, 240));
            certPanel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
            
            // Add icon
            JLabel icon = new JLabel("Certificate");
            icon.setFont(new Font("Arial", Font.BOLD, 14));
            certPanel.add(icon);
            
            // Add course name
            JLabel courseName = new JLabel(c.getCourseTitle());
            courseName.setFont(new Font("Arial", Font.PLAIN, 12));
            certPanel.add(courseName);
            
            // Add score
            JLabel score = new JLabel("Score: " + c.getFinalScore() + "%");
            score.setFont(new Font("Arial", Font.PLAIN, 11));
            certPanel.add(score);
            
            // Add view button
            JButton viewBtn = new JButton("View");
            final Certificate cert = c; // for the button click
            viewBtn.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    showCertificate(cert);
                }
            });
            certPanel.add(viewBtn);
            
            panel.add(certPanel);
            panel.add(Box.createVerticalStrut(5));
        }
    }
    
    // Add to scroll pane
    JScrollPane scroll = new JScrollPane(panel);
    dialog.add(scroll);
    
    // Show dialog
    dialog.setVisible(true);
    }//GEN-LAST:event_certificatesBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
 int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to logout?",
        "Confirm Logout",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Close current window
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
        
        // Open login frame
        new LoginFrame().setVisible(true);
    }    }//GEN-LAST:event_logoutBtnActionPerformed
private void showCertificate(Certificate cert) {
    // Get the parent frame
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    
    // Create the certificate dialog and pass the certificate data
    CertificateDialog dialog = new CertificateDialog(parentFrame, cert);
    
    // Show the dialog
    dialog.setVisible(true);
}

private void loadEnrolledCourses() {
        DefaultListModel<String> model = new DefaultListModel<>();
        try {
            List<Course> courses = service.getEnrolledCourses(student.getUserId());
            
            if (courses.isEmpty()) {
                model.addElement("No enrolled courses yet");
            } else {
                for (Course c : courses) {
                    model.addElement(c.getCourseID() + " - " + c.getCourseTitle());
                }
            }
            
            enrolledList.setModel(model);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading enrolled courses: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            model.addElement("Error loading courses");
            enrolledList.setModel(model);
        }
    }
private void loadAvailableCourses() {
    DefaultListModel<String> model = new DefaultListModel<>();
    try {
        for (Course c : service.browseAvailableCourses()) {
            model.addElement(c.getCourseID() + " - " + c.getCourseTitle());
        }
        availableList.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error loading available courses: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        model.addElement("Error loading courses");
        availableList.setModel(model);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableLabel;
    private javax.swing.JList<String> availableList;
    private javax.swing.JPanel availablePanel;
    private javax.swing.JButton certificatesBtn;
    private javax.swing.JButton enrollBtn;
    private javax.swing.JLabel enrolledLabel;
    private javax.swing.JList<String> enrolledList;
    private javax.swing.JPanel enrolledPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton openBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
